"""
Safe Response and Remediation Schema (v1.0.0).
Enforces Human-in-the-Loop approval, allowlisted actions, dry-run mode, and rollback contracts.
"""
from datetime import datetime, timezone
from enum import Enum
from typing import Optional, List, Dict, Any
from uuid import uuid4
from pydantic import BaseModel, Field


class ResponseActionType(str, Enum):
    BLOCK_IP = "block_ip"
    UNBLOCK_IP = "unblock_ip"
    DISABLE_USER = "disable_user"
    ENABLE_USER = "enable_user"
    ISOLATE_HOST = "isolate_host"
    UNISOLATE_HOST = "unisolate_host"
    KILL_PROCESS = "kill_process"
    QUARANTINE_FILE = "quarantine_file"


class ApprovalStatus(str, Enum):
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"
    EXPIRED = "expired"


class ExecutionStatus(str, Enum):
    PROPOSED = "proposed"
    DRY_RUN_PASSED = "dry_run_passed"
    DRY_RUN_FAILED = "dry_run_failed"
    EXECUTING = "executing"
    COMPLETED = "completed"
    FAILED = "failed"
    ROLLED_BACK = "rolled_back"


class ResponseRecommendation(BaseModel):
    """Proposed defensive mitigation generated by Agent E."""
    recommendation_id: str = Field(default_factory=lambda: f"REC-{uuid4().hex[:8].upper()}")
    incident_id: str
    action_type: ResponseActionType
    target: str = Field(..., description="Target IP, username, hostname, or process name")
    justification: str
    evidence_ids: List[str] = Field(default_factory=list)
    operational_impact: str = Field(..., description="Potential collateral impact on legitimate business ops")
    prerequisites: List[str] = Field(default_factory=list)
    rollback_procedure: str
    dry_run_supported: bool = True
    approval_required: bool = True
    suggested_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class HumanApproval(BaseModel):
    """Explicit human sign-off recorded before executing any action with operational impact."""
    approval_id: str = Field(default_factory=lambda: f"APP-{uuid4().hex[:8].upper()}")
    recommendation_id: str
    incident_id: str
    approver_username: str
    approver_role: str = "SOC_LEAD"
    status: ApprovalStatus = ApprovalStatus.PENDING
    decision_timestamp: Optional[datetime] = None
    reason: Optional[str] = None
    signature: Optional[str] = None


class ResponseExecution(BaseModel):
    """Audit log of dry-run or live execution of an approved mitigation."""
    execution_id: str = Field(default_factory=lambda: f"EXE-{uuid4().hex[:8].upper()}")
    recommendation_id: str
    approval_id: Optional[str] = None
    action_type: ResponseActionType
    target: str
    dry_run: bool = False
    status: ExecutionStatus = ExecutionStatus.PROPOSED
    executed_by: str = "SOC_CONTROL_PLANE"
    executed_at: Optional[datetime] = None
    duration_ms: int = 0
    logs: List[str] = Field(default_factory=list)
    rollback_supported: bool = True
    is_rolled_back: bool = False
    rollback_timestamp: Optional[datetime] = None
    error_message: Optional[str] = None
